- name: Profile a PipeEdge model
  hosts: all

  vars:
    venv_dir: "{{ ansible_env.HOME }}/venv-PipeEdge"
    source_dir: "{{ ansible_env.HOME }}/PipeEdge"
    models_dir: "{{ ansible_env.HOME }}/models"
    results_yml: "profiler_results.yml"
    model_name: "google/vit-base-patch16-224"
    model_file: "{{ ansible_env.HOME }}/models/ViT-B_16-224.npz"
    microbatch_size: 8
    iterations: 10

  tasks:

  - name: Check if results file exists
    ansible.builtin.stat:
      path: "{{ results_yml }}"
    register: results_file

  - name: Fail if results file exists
    ansible.builtin.fail:
      msg: "Profile results file already exists: {{ results_yml }}"
    when: results_file.stat.exists

  - name: Profile
    shell: |
      source "{{ venv_dir }}/bin/activate" && \
      python3 "{{ source_dir }}/profiler.py" -w -i "{{ iterations }}" \
        -o "{{ results_yml }}" -m "{{ model_name }}" -M "{{ model_file }}" \
        -b "{{ microbatch_size }}" \
        > >(tee stdout.log) 2> >(tee stderr.log)
    args:
      executable: /bin/bash
