- name: Upgrade apt packages
  hosts: all
  become: yes

  tasks:

  # Prevent grub upgrades: RCC-VE devices use grub2, Minnowboards use grub-efi.
  # On RCC-VE devices, grub still presents an interactive GUI complaining about
  # the installation disk (at least with apt-get, even when using
  # DEBIAN_FRONTEND=noninteractive).
  # On Minnowboards, grub also complains, though without a blocking GUI.
  - name: Dpkg hold grub2
    ansible.builtin.dpkg_selections:
      name: grub2
      selection: hold
  - name: Dpkg hold grub-efi
    ansible.builtin.dpkg_selections:
      name: grub-efi
      selection: hold

  # TODO: how can we pass "--allow-releaseinfo-change" to apt module instead?
  - name: Apt update
    ansible.builtin.command:
      argv:
        - apt-get
        - --allow-releaseinfo-change
        - update

  # dist-upgrade is apparently needed to get kernel updates (maybe since we're blocking grub)
  - name: Apt dist-upgrade
    apt:
      upgrade: dist

  - name: Check reboot-required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists
