- name: Install cnpy
  hosts: all

  vars:
    source_dir: cnpy
    build_dir: "{{source_dir}}/build"
    version: 4e8810b
    build_type: RelWithDebInfo

  tasks:

  - name: Install apt dependencies
    become: yes
    apt:
      name:
        - build-essential
        - cmake
        - git
        - zlib1g-dev

  - name: Fetch source
    ansible.builtin.git:
      repo: 'https://github.com/rogersce/cnpy.git'
      dest: "{{ source_dir }}"
      version: "{{ version }}"
    register: source

  - name: Create build directory
    command: cmake -S "{{ source_dir }}" -B "{{ build_dir }}" \
             -DCMAKE_BUILD_TYPE="{{ build_type }}" \
             -DENABLE_STATIC=OFF
    args:
      creates: "{{build_dir}}"
    when: source.changed

  - name: Uninstall
    become: yes
    file:
      path: "{{ item }}"
      state: absent
    loop:
      - /usr/local/lib/libcnpy.so
      - /usr/local/include/cnpy.h
      - /usr/local/bin/mat2npz
      - /usr/local/bin/npy2mat
      - /usr/local/bin/npz2mat
    when: source.changed

  - name: Compile
    command: cmake --build "{{ build_dir }}" -j
    when: source.changed

  - name: Install
    become: yes
    command: cmake --build "{{ build_dir }}" -j --target install
    when: source.changed

  - name: Run ldconfig
    become: yes
    command: ldconfig
    when: source.changed
