- name: Install EdgePipe
  hosts: all

  vars:
    # ansible_python_interpreter: /usr/bin/python3
    source_dir: "{{ ansible_env.HOME }}/EdgePipe"
    version: fogsys_integration
    models_dir_local: /tmp/edgepipe/models
    models_dir: "{{ ansible_env.HOME }}/models"
    venv_dir: "{{ ansible_env.HOME }}/venv-EdgePipe"

  tasks:

  - name: Install apt dependencies
    become: yes
    local_action:
      module: ansible.builtin.apt
      name:
        - git
        - python3-venv
    run_once: true

  - name: Create models directory on controller
    local_action:
      module: ansible.builtin.file
      path: "{{ models_dir_local }}"
      state: directory
    run_once: true

  - name: Download ViT models to controller
    local_action:
      module: ansible.builtin.get_url
      url: "{{ item.url }}"
      dest: "{{ models_dir_local }}/{{ item.file }}"
    loop:
      # Explicitly specifying a file rather than just the dest directory avoids
      # downloading the large files every time this task is invoked.
      - { url: 'https://storage.googleapis.com/vit_models/imagenet21k%2Bimagenet2012/ViT-B_16-224.npz', file: 'ViT-B_16-224.npz' }
      - { url: 'https://storage.googleapis.com/vit_models/imagenet21k%2Bimagenet2012/ViT-L_16-224.npz', file: 'ViT-L_16-224.npz' }
      - { url: 'https://storage.googleapis.com/vit_models/imagenet21k/ViT-H_14.npz', file: 'ViT-H_14.npz' }
    run_once: true

  - name: Copy ViT models from controller to hosts
    ansible.builtin.copy:
      src: "{{ models_dir_local }}/"
      dest: "{{ models_dir }}/"
      force: no

  # TODO: BERT runs out of memory on MinnowBoards - do everything on XDC

  # - name: Cache BERT models
  #   shell: |
  #     source "{{ venv_dir }}/bin/activate" && \
  #     python3 "{{ source_dir }}/tools/bert_save_weights.py"
  #   args:
  #     chdir: "{{ models_dir }}"
  #     executable: /bin/bash
  #     creates: "{{ models_dir }}/BERT-L.npz"

  # - name: Cache DeiT models
  #   shell: |
  #     source "{{ venv_dir }}/bin/activate" && \
  #     python3 "{{ source_dir }}/tools/deit_save_weights.py"
  #   args:
  #     chdir: "{{ models_dir }}"
  #     executable: /bin/bash
  #     creates: "{{ models_dir }}/DeiT_T_distilled.npz"
